In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [2]:
df=pd.read_csv("/home/hardwarelab00/Downloads/Iris.csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
df.shape()

TypeError: 'tuple' object is not callable

In [7]:
df.shape

(150, 6)

In [9]:
df.mean(numeric_only=True)

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [10]:
df.median(numeric_only=True)

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [11]:
data.species.mode()

NameError: name 'data' is not defined

In [12]:
df.Species.mode()

0        Iris-setosa
1    Iris-versicolor
2     Iris-virginica
Name: Species, dtype: object

In [13]:
df.groupby(["Species"]).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [14]:
df.SepalLengthCm.std()

0.828066127977863

In [15]:
df.SepalWidthCm.std()

0.4335943113621737

In [16]:
df.PetalLengthCm.std()

1.7644204199522626

In [17]:
df.PetalLengthCm.std()

1.7644204199522626

In [18]:
df.PetalWidthCm.std()

0.7631607417008411

In [19]:
df.rename(columns={'SepalLengthCm':'NEWSepalLengthCm','SepalWidthCm':'NEWSepalWidthCm','PetalLengthCm':'NEWPetalLengthCm','PetalWidthCm':'NEWPetalWidthCm'},inplace=True)

In [21]:
print("Column renaming... Table after Renaming columns")
df.head()

Column renaming... Table after Renaming columns

,Id,NEWSepalLengthCm,NEWSepalWidthCm,NEWPetalLengthCm,NEWPetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa